# Generated by Django 5.2.8 on 2025-11-25 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Friendly name, e.g. 'Personal Gmail' or 'NavonLogic'.", max_length=128)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Microsoft 365'), ('yahoo', 'Yahoo'), ('imap', 'Generic IMAP')], default='imap', max_length=32)),
                ('email_address', models.EmailField(max_length=254)),
                ('imap_server', models.CharField(blank=True, default='', max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('smtp_server', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, default='', help_text='Usually same as email address.', max_length=255)),
                ('password', models.CharField(blank=True, default='', help_text='For app passwords or temporary testing only. Prefer OAuth in production.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text="Stable provider ID or IMAP UID so we don't import duplicates.", max_length=255)),
                ('folder', models.CharField(choices=[('INBOX', 'Inbox'), ('SENT', 'Sent'), ('DRAFTS', 'Drafts'), ('ARCHIVE', 'Archive'), ('TRASH', 'Trash'), ('OTHER', 'Other')], default='INBOX', max_length=32)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('from_email', models.CharField(blank=True, default='', max_length=512)),
                ('to_emails', models.TextField(blank=True, default='')),
                ('cc_emails', models.TextField(blank=True, default='')),
                ('bcc_emails', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.emailaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('account', 'external_id')},
            },
        ),
    ]
