# Generated by Django 5.2.8 on 2025-11-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_note_job_noteattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='job',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
